### ISSUE TITLE
[BUG]cannot convert from 'string' to 'char'

### ISSUE THREAD

**Issue by ldgz123** [VeriorPies/ParrelSync#116]
### cannot convert from 'string' to 'char'
Library/PackageCache/com.veriorpies.parrelsync@141b4e1e31/Editor/Preferences.cs(91,31): error CS1503: Argument 1: cannot convert from 'string' to 'char'

**Comment by ldgz123** [comment]
![image](https://github.com/VeriorPies/ParrelSync/assets/24666709/bd214fba-f359-4caa-8842-58cd2b80a3f7)

**Comment by RafaelChavesSM** [comment]
Currently having the same bug

**Comment by RafaelChavesSM** [comment]
I believe I fixed it doing:
``` csharp
return data.Split(serializationToken.ToCharArray()).ToList();
```

**Comment by Katerlad** [comment]
Fresh install of 1.5.2 also caused this error for me as well.

**Comment by Awais6** [comment]
same here

**Comment by gakkossphynx** [comment]
`return data.Split(serializationToken.ToCharArray()).ToList();`

**Comment by 314pies** [comment]
For anyone who's running into this issue - would you mind sharing which Unity version you are using?

**Comment by gpiffaretti** [comment]
Unity version 2021.1.28f1

**Comment by 314pies** [comment]
Hi all,  
Here're some investigation results:  
- The is caused by the different in `String.Split()` between [.NET Standard 2.0](https://learn.microsoft.com/en-us/dotnet/api/system.string.split?view=netstandard-2.0#system-string-split(system-string()-system-stringsplitoptions)) (used by Unity 2021.1.28) and [.NET Standard 2.1](https://learn.microsoft.com/en-us/dotnet/api/system.string.split?view=netstandard-2.1#system-string-split(system-string-system-stringsplitoptions)) (used by more recent Unity version) 
- The changes above (`return data.Split(serializationToken.ToCharArray()).ToList();`) will change the function behavior, which will break the optional symbolic folders feature.  
  - [Split(Char[], StringSplitOptions)](https://learn.microsoft.com/en-us/dotnet/api/system.string.split?view=netstandard-2.0#system-string-split(system-char()-system-stringsplitoptions)) => Split based on list of character
  - [Split(String, StringSplitOptions)](https://learn.microsoft.com/en-us/dotnet/api/system.string.split?view=netstandard-2.1#system-string-split(system-string-system-stringsplitoptions)) => Split based on "a" string
 - A more proper fixes for `.NET Standard 2.0` capability will be:  
     ``` 
     return data.Split(new string[] { serializationToken }, System.StringSplitOptions.None).ToList();
     ```

A fixes should be out soon.

**Comment by 314pies** [comment]
Fixes is now available on `dev` branch: https://github.com/VeriorPies/ParrelSync/commit/dc06daf27edafa275f035fdf67667625c84f9653

Waiting to be released to main branch.
