### ISSUE TITLE
[BUG] ClonesManager opening unity hub

### ISSUE THREAD

**Issue by ultraflame4** [VeriorPies/ParrelSync#19]
**Describe the bug**
The clones manager is opening unity hub instead of an Editor

**To Reproduce**
1. Go to ClonesManager > Clone 0
2. Click on 'Open in New Editor'
3. Unity Editor loads for a second
4. The editor loading screen closes and unity hub appears

**Expected behavior**
The editor should have finished loading such that there is another instance

**Screenshots/Video**
If applicable, add screenshots or video link( Youtube/Vimeo) to help explain the problem.

[video.zip](https://github.com/VeriorPies/ParrelSync/files/5594131/video.zip)

**Enviroment (please complete the following information):**
 - Unity Editor Version: Windows 10 Unity 2019.4.15f1 Personal
 - ParrelSync Version 1.4.1

**Additional context**

**Comment by 314pies** [comment]
Hi ultraflame4,
Can you open the clone project directly from the Unity Hub?
If can't, have you try to delete the clone and create another one.

**Comment by ultraflame4** [comment]
I'll try that later thanks!

**Comment by ultraflame4** [comment]
Uh i cant add the project, it says : "Invalid project path"

**Comment by 314pies** [comment]
If the clone project can't be opened directly by Unity, than this issue is probably due to Unity not recognizing the clone project folder as an Unity Project.
What's the clone project folder look like?

A typical Unity project folder should be something like this:
![image](https://user-images.githubusercontent.com/20402192/100607547-0d5f2a80-3346-11eb-9288-26bc96abd9c2.png)

What's is the log message printed in console when opening clone project?
And if possible, would you mind to share a project that can reproduce this issue?
(Sorry for the late reply, very busy these days. Will still try my best to reply ASAP)

**Comment by ultraflame4** [comment]
Here is a screenshot of the output in unity's console
![image](https://user-images.githubusercontent.com/34125174/100617588-af3a4380-3355-11eb-993e-94b72a33e8dc.png)


Screenshot of the clone project folder:
![image](https://user-images.githubusercontent.com/34125174/100617735-e0b30f00-3355-11eb-92bd-a49df73c3ca5.png)

Here is a recording of me trying to create and open a clone:
[recording.zip](https://github.com/VeriorPies/ParrelSync/files/5616276/recording.zip)

I'll try to give you a github link (its on github) to the project if you want.

**Comment by ultraflame4** [comment]
Here: https://github.com/ultraflame4/Take2/archive/v0.0.0a.zip

**Comment by 314pies** [comment]
I've tried your project, the newly created clone work just fine on my machine.
I think this problem is related to your OS (with screenshot you shared, every folder required linking are missing)
Can you run your Unity editor with Administration permission and try it again?
If still can't work, try to manually create folders and type the ```mklink /J``` command to link the new folder with original and see if there's any error message popup.

**Comment by ultraflame4** [comment]
uh, it says "Local NTFS volumes are required to complete the operation."

**Comment by 314pies** [comment]
Never handled this error before.
Have you found the reason yet?

**Comment by ultraflame4** [comment]
Yeah i just found the reason.
 symlinks are not supported on the exFat File system... and the project is on my external exFat drive...
I'll guess i have to move the project to the C drive then.
